---
title: "Flu model documentation"
output: html_document
date: "2024-06-10"
author: "Fanny Bergström"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This document describes an age and vaccination dissaggregated SIR model.
We are fitting the model to weekly ILI incidence multiplied by flu-positivity in that same week. 

## SIR

We consider a population consisting of $N$ individuals.  The population is divided into three compartments: the susceptible, infectious and removed compartments. Their sizes, at any time $t$ for an age class $j$, are denoted by $S^{(j)}(t)$, $I^{(j)}(t)$ and $R^{(j)}(t)$ respectively. We also use a community contact rate $\beta$. We let the rate of recovery be denoted $\gamma$.

We use a contact matrix $C$, with elements $C_{i,j}$ being the average number of contacts an individual in age group $i$ has with individuals in age group $j$ within 24h. 

We let $vax(t)$ be the fraction of new people being vaccinated on day $t$. Subscript $u$ and $v$ are used to distinguish between the unvaccinated and vaccinated groups. We further let $ve_{inf}$, $ve_{susc}$ and $ve_{severe}$ be the vaccine efficacy in terms of infectiousness, susceptibility and severe disease. 

The SIR model is specified as follows

\begin{aligned}
S_u^{(j)}(t) & = S_u^{(j)}(t-1) - vax^{(j)}(t-1) \frac{S_u^{(j)}(t-1) }{S_u^{(j)}(t-1) +R_u^{(j)}(t-1) }\\
   & -\beta\sum_{i} C_{i,j}  \big(I_u^{(i)}(t-1)+ (1-ve_{inf}) (I_{v}^{(i)}(t-1)\big) S_u^{(j)}(t-1) \\
   \\
 S_{v}^{(j)}(t) & = S_{v}^{(j)}(t-1) + vax^{(j)}(t-1) \frac{S_u^{(j)}(t-1) }{S_u^{(j)}(t-1)  +R_u^{(j)}(t-1) }\\
  &-\beta\sum_{i} C_{i,j}  \big(I_u^{(i)}(t-1)+ (1-ve_{inf}) (I_{v}^{(i)}(t-1)\big)     S_{v}^{(j)(t-1)}(1-ve_{susc}) \\
\\
I_u^{(j)}(t) & = I_u^{(j)}(t-1)+ \beta\sum_{i} C_{i,j}  \big(I_u^{(i)}(t-1)+ (1-ve_{inf}) (I_{v}^{(i)}(t-1)\big) S_u^{(j)}(t-1) - \gamma I_u^{(j)}(t - 1)  \\
                \\
I_{v}^{(j)}(t) & = I_{v}^{(j)}(t-1) + \beta\sum_{i} C_{i,j}  \big(I_u^{(i)}(t-1)+ (1-ve_{inf}) (I_{v}^{(i)}(t-1)\big) S_{v}^{(j)}(t-1) - \gamma I_{v}^{(j)}(t - 1)  \\
                \\                
R_u^{(j)}(t) & = R_u^{(j)}(t-1) + \gamma I_u^{(j)}(t - 1) - vax^{(j)}(t-1) \frac{R_u^{(j)}(t-1) }{S_u^{(j)}(t-1) + R_u^{(j)}(t-1) } \\ 

R_{v}^{(j)}(t) & = R_{v}^{(j)}(t-1) + \gamma I_{v}^{(j)}(t - 1) + vax^{(j)}(t-1) \frac{R_u^{(j)}(t-1) }{S_u^{(j)}(t-1) + R_u^{(j)}(t-1) }.

\end{aligned}


We let both susceptible and recovered be vaccinated proportional to their size at time $t$, assuming that you will not get vaccinated during the time of being infectious.

## Statistical inference

We assume an Negative Binomial distribution for the weekly ILI incidence multiplied by the flu positivity for that week.

The SIR model is fitted on a daily scale and then 

$$
\text{weekly ILI for age group } i \text{ at time } t\sim \text{NegBin}( \mu(t)^i, \phi ),
$$
where $\mu(t)^i$ is the mean of the severe outcomes for age group $i$ for week $t$ and $\phi$ is the overdispersion parameter.

## Data

For the contact matrix $C$, we use estimated from the study ["Projecting social contact matrices in 152 countries using contact surveys and demographic data" (Prem et al, 2017)](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005697). This study provides model based estimates of the expected number of contacts of an individual in age-group $i$ with individuals from age-group $j$ within 24h.


